import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Button } from "@/components/ui/button";
import { Heart, ArrowRight } from "lucide-react";
export const Hero = () => {
    const scrollToBooking = () => {
        document.getElementById('agendamento')?.scrollIntoView({ behavior: 'smooth' });
    };
    return (_jsxs("section", { className: "relative min-h-[90vh] flex items-center justify-center overflow-hidden bg-gradient-to-br from-primary/20 via-background to-accent/20 px-4 py-20", children: [_jsx("div", { className: "absolute inset-0 bg-[url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjAiIGhlaWdodD0iNjAiIHZpZXdCb3g9IjAgMCA2MCA2MCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48ZyBmaWxsPSJub25lIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiPjxnIGZpbGw9IiNGQkUxODYiIGZpbGwtb3BhY2l0eT0iMC4xIj48cGF0aCBkPSJNMzYgMzRjMC0yLjIxLTEuNzktNC00LTRzLTQgMS43OS00IDQgMS43OSA0IDQgNCA0LTEuNzkgNC00em0wLTEwYzAtMi4yMS0xLjc5LTQtNC00cy00IDEuNzktNCA0IDEuNzkgNCA0IDQgNC0xLjc5IDQtNHptMC0xMGMwLTIuMjEtMS43OS00LTQtNHMtNCAxLjc5LTQgNCAxLjc5IDQgNCA0IDQtMS43OSA0LTR6Ii8+PC9nPjwvZz48L3N2Zz4=')] opacity-40" }), _jsx("div", { className: "container mx-auto max-w-6xl relative z-10", children: _jsxs("div", { className: "text-center space-y-8 animate-fade-in", children: [_jsxs("div", { className: "inline-flex items-center gap-2 bg-coral/20 text-coral-foreground px-6 py-2 rounded-full text-sm font-medium animate-scale-in", children: [_jsx(Heart, { className: "w-4 h-4 fill-coral" }), _jsx("span", { children: "Atendimento com amor e prop\u00F3sito" })] }), _jsxs("h1", { className: "font-heading text-4xl md:text-6xl lg:text-7xl font-bold leading-tight text-foreground", children: ["Cuidar do desenvolvimento", _jsx("br", {}), _jsx("span", { className: "bg-gradient-to-r from-primary via-coral to-accent bg-clip-text text-transparent", children: "\u00E9 o primeiro passo" })] }), _jsx("p", { className: "text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto leading-relaxed", children: "Especialistas em psicopedagogia, psicologia infantil e fonoaudiologia trabalhando juntos pelo melhor desenvolvimento do seu filho." }), _jsxs("div", { className: "flex flex-col sm:flex-row gap-4 justify-center items-center pt-4", children: [_jsxs(Button, { variant: "cta", size: "lg", onClick: scrollToBooking, className: "group", children: ["Agendar atendimento", _jsx(ArrowRight, { className: "w-5 h-5 group-hover:translate-x-1 transition-transform" })] }), _jsx(Button, { variant: "outline", size: "lg", children: "Conhe\u00E7a nossa equipe" })] }), _jsx("div", { className: "pt-12 grid grid-cols-1 md:grid-cols-3 gap-6 max-w-3xl mx-auto", children: [
                                { number: "10+", label: "Anos de experiência" },
                                { number: "500+", label: "Famílias atendidas" },
                                { number: "3", label: "Especialidades integradas" }
                            ].map((stat, index) => (_jsxs("div", { className: "bg-card/80 backdrop-blur-sm rounded-2xl p-6 shadow-soft animate-slide-up", style: { animationDelay: `${index * 100}ms` }, children: [_jsx("div", { className: "font-heading text-3xl font-bold text-primary mb-1", children: stat.number }), _jsx("div", { className: "text-sm text-muted-foreground", children: stat.label })] }, index))) })] }) }), _jsx("div", { className: "absolute top-20 left-10 w-20 h-20 bg-secondary/30 rounded-full blur-2xl animate-pulse" }), _jsx("div", { className: "absolute bottom-20 right-10 w-32 h-32 bg-accent/30 rounded-full blur-3xl animate-pulse", style: { animationDelay: '1s' } })] }));
};
//# sourceMappingURL=Hero.js.map